app/csudadmin/__init__.py
from flask import Blueprint

csudadmin = Blueprint('csudadmin', __name__, template_folder='templates/csudadmin')

from . import views

app/csudadmin/views.py
from flask import render_template, session, redirect, url_for, current_app, request, g
from .. import db
from ..models import *

from ..email import send_email
from . import csudadmin as admin
from sqlalchemy.sql import select
from sqlalchemy import func, text, desc

from flask import copy_current_request_context

from flask.ext.login import LoginManager, UserMixin, login_user, logout_user, login_required, current_user

'''
'''

@admin.route('/')
def index():
    return render_template('admin_index.html')

app/csudadmin/templates/csudadmin/admin_base.html
{% extends "base.html" %}

{% block title %}CSUD Réservation (Admin){% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="stylesheet" href="{{ url_for('static', filename='custom.css') }}">
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Activer la navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('csudadmin.index') }}">Admin Réservations</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                {% if current_user.is_authenticated %}
                    <li><a href="{{ url_for('main.search_page') }}">Réservation</a></li>
                    <li><a href="{{ url_for('main.horaire') }}">Horaires</a></li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                    <li><a href="{{ url_for('main.my_reservations') }}">Mes réservations</a></li>
                    <li><a href="{{ url_for('main.profil') }}">Profil</a></li>
                    <li><a href="{{ url_for('main.logout') }}">Logout</a></li>
                {% else %}
                    <li><a href="{{ url_for('main.login') }}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
<script src="{{ url_for('static', filename='general.js') }}"></script>
{% endblock %}

app/csudadmin/templates/csudadmin/admin_index.html
{% extends "admin_base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<div class="page-header">
    <h1>Zone d'administration</h1>
    {{ message }}<br>

</div>
{% endblock %}